### PR TITLE
Feature/add drug exposure table

### PR DESCRIPTION
**Pull request by calmacx**
depends on #167 

image

### CODE REVIEW

**Comment by calmacx** [comment]
> @calmacx what stage is this PR at? Thanks.

@spco i actually spoke with Erum about this yesterday and she said for the drug_exposure table they dont need anything in addition, meaning that this PR is good to go now actually. 

They only need to 6 rules shown in the screenshot, nothing else (at current).

**Comment by spco** [comment]
Ok, so this now just contains the changes in `services_rules.py` - to clarify, that is all that's currently needed?

**Comment by calmacx** [comment]
hi @spco indeed this is all that is needed to turn on this particular table in the mapping tool.

What don't you think matches up with the ticket? In the ticket they say the only fields they need are the person_id, concept_id and start date. By turning this table on, they'll also get the source_value and source_concept_id (which IMO should be included) and the end date (which can be removed if really necessary)

Or am I missing something? cheers

**Comment by spco** [comment]
This doesn't explicitly mention `drug_concept_id` - so I'm guessing that is exposed through the `drug_exposure` table? I was just thinking that your force-push removed quite a lot of code so wanted to check.

**Comment by calmacx** [comment]
> This doesn't explicitly mention `drug_concept_id` - so I'm guessing that is exposed through the `drug_exposure` table? I was just thinking that your force-push removed quite a lot of code so wanted to check.

That's right, I have a dump of the Omop table/fields we are using (v5.3.1) here: https://github.com/CO-CONNECT/co-connect-tools/blob/master/coconnect/data/cdm/OMOP_CDM_ONLINE_LATEST.csv#L32

Yeh no worries, the force was from a rebase and it does look odd that this is all that is needed :)

**Pull request merged**
