### PR TITLE
Show only parent dataset users

### PR DESCRIPTION
**Pull request by Samad198**
# Changes
- Added the ability to add viewers and editors to scanreport upload
- Added the ability to add editors and admins to dataset upload in scanreport upload page

# Migrations

# Screenshots
image
image

# Todo
- 
- 
# Checks

**Important:** please complete these **before** merging.
- [ ] Run migrations, if any.
- [ ] Update `changelog.md`, including migration instructions if any.
- [ ] Run unit tests.

### CODE REVIEW

**Comment by spco** [comment]
Looks good so far.

**Comment by Samad198** [comment]
Have been able to make the newly added dataset show up in the list without reloading the page. It seems to be because the fetch request is returning a cached value but I have added no cach headers to the request and still got the same result
Have tried headers:
- 'Cache-Control': 'no-store'
- 'pragma': 'no-cache'
- 'Cache-Control': 'no-cache',

**Comment by spco** [comment]
Sorry, to clarify, have you been able or unable to get the new Dataset to appear in the list? If not, I don't think it's too big a deal. Most people if they are creating a new Dataset are then going to immediately upload a new SR to it, without changing the selection in the Dataset dropdown. So as long as the following works:

1. Create new Dataset X
2. Upload new SR to Dataset X without refreshing the page

Then I'm happy enough if this is just wasting your time hunting for a fix. Can you confirm please?

**Comment by Samad198** [comment]
> 1. taset X

You can't currently do that, but I will be able to implement that since the endpoint for creating the dataset returns the newly created dataset. I'll implement that now

**Comment by Samad198** [comment]
> Sorry, to clarify, have you been able or unable to get the new Dataset to appear in the list? If not, I don't think it's too big a deal. Most people if they are creating a new Dataset are then going to immediately upload a new SR to it, without changing the selection in the Dataset dropdown. So as long as the following works:
> 
> 1. Create new Dataset X
> 2. Upload new SR to Dataset X without refreshing the page
> 
> Then I'm happy enough if this is just wasting your time hunting for a fix. Can you confirm please?

Have now found out why newly created datasets were not showing up and have updated the code to fix that. Can now as a result complete those actions

**Review by dcl10 — APPROVED** [review]

**Pull request merged**
