### PR TITLE
Fix/19

### PR DESCRIPTION
**Pull request by calmacx**
Fix bug for #19

### CODE REVIEW

**Comment by simon-tarr** [comment]
@calmacx presumably this fix lets you upload the offending scan report without any further issues? Have you been able to get hold of any other reports to test?

**Comment by calmacx** [comment]
@simon-tarr just added another little (temp) fix needed  for the last sheet of the WhiteRabbit report which has these sheets just named '_' 🤷 

I've tested it working on the PANTHER report as well as this GOSH one from Erum. Only ones I have to test on

**Comment by simon-tarr** [comment]
I'm snowed at the minute but will try and get round to merging this before the end of today.

**Comment by simon-tarr** [comment]
@calmacx  or you can ask @vasilikipn to review and merge?

**Pull request merged**
